apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    # ใส่กลับเข้าไปเพื่อบังคับให้ controller อ่านไฟล์นี้
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx 
  rules:
  - host: jenkins.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins-service
            port:
              number: 80